version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '3002:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
